### PR TITLE
Added ability to specify browser version constraints and download And…

### LINKED ISSUE #155: Add ability to download only specified browser versions
Something like: `./cm selenoid start --browsers chrome=65.0,firefox=57.0`. Also support semver expressions like: https://github.com/blang/semver

### LINKED ISSUE #159: Add ability to download Android images
Do not download by default. Only when called like this: `./cm selenoid start --browsers "android"`

### PR DESCRIPTION
**Pull request by vania-pooh**
…roid images (fixes #155, fixes #159)

### CODE REVIEW

**Comment by da-yaroslav-orel** [comment]
@vania-pooh is this also available for Windows cm executable?

**Comment by vania-pooh** [comment]
@da-yaroslav-orel should work on any OS for Docker. For drivers mode - makes no sense as latest versions are always downloaded.

**Comment by da-yaroslav-orel** [comment]
@vania-pooh understood. but it's sometimes convenient to have option to specify which driver you want. For example if we want to run tests on older browsers which are compatible with older drivers.  Is this possible to consider adding this feature for binaries mode?

**Comment by vania-pooh** [comment]
@da-yaroslav-orel do add this we have to maintain a big file with correct URLs for every version and architecture. Currently it is too much work. Take a look at current file: https://github.com/aerokube/cm/blob/master/browsers.json Already a lot of info. If you multiply this by number of different driver versions - this file will be enormous.

**Comment by da-yaroslav-orel** [comment]
@vania-pooh I think there should be a way to download drivers without hardcoding urls. Webdriver manager https://github.com/bonigarcia/webdrivermanager allows to specify driver versions to download.

**Comment by vania-pooh** [comment]
@da-yaroslav-orel too much manual work in our rapidly changing world. :)

**Pull request merged**
